--
-- PostgreSQL database dump
--

-- Dumped from database version 14.9
-- Dumped by pg_dump version 14.9

-- Started on 2023-10-15 20:55:12

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 211 (class 1259 OID 33189)
-- Name: TaskItems; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."TaskItems" (
    "Id" bigint NOT NULL,
    "Name" character(128),
    "Description" character(1024),
    "DueDate" character(10),
    "CreationDate" character(10),
    "CompletionDate" character(10),
    "Status" integer NOT NULL,
    "IsDeleted" integer NOT NULL
);


ALTER TABLE public."TaskItems" OWNER TO postgres;

--
-- TOC entry 210 (class 1259 OID 33188)
-- Name: TaskItems_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."TaskItems" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."TaskItems_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 213 (class 1259 OID 33197)
-- Name: Users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."Users" (
    "Id" bigint NOT NULL,
    "FirstName" text,
    "LastName" text,
    "Patronymic" text,
    "Username" text,
    "Email" text,
    "Password" text
);


ALTER TABLE public."Users" OWNER TO postgres;

--
-- TOC entry 212 (class 1259 OID 33196)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 33183)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


ALTER TABLE public."__EFMigrationsHistory" OWNER TO postgres;

--
-- TOC entry 3320 (class 0 OID 33189)
-- Dependencies: 211
-- Data for Name: TaskItems; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."TaskItems" ("Id", "Name", "Description", "DueDate", "CreationDate", "CompletionDate", "Status", "IsDeleted") FROM stdin;
1	swim                                                                                                                            	in a pool                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       	2023-10-15	2023-10-15	2023-10-15	2	0
2	walk                                                                                                                            	in a park                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       	2023-10-18	2023-10-15	2023-10-15	2	0
\.


--
-- TOC entry 3322 (class 0 OID 33197)
-- Dependencies: 213
-- Data for Name: Users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."Users" ("Id", "FirstName", "LastName", "Patronymic", "Username", "Email", "Password") FROM stdin;
1	john	smith	mcsmith	admin	wer@asddas.ru	admin
\.


--
-- TOC entry 3318 (class 0 OID 33183)
-- Dependencies: 209
-- Data for Name: __EFMigrationsHistory; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."__EFMigrationsHistory" ("MigrationId", "ProductVersion") FROM stdin;
20231014050829_initial	5.0.17
\.


--
-- TOC entry 3328 (class 0 OID 0)
-- Dependencies: 210
-- Name: TaskItems_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."TaskItems_Id_seq"', 2, true);


--
-- TOC entry 3329 (class 0 OID 0)
-- Dependencies: 212
-- Name: Users_Id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."Users_Id_seq"', 1, true);


--
-- TOC entry 3176 (class 2606 OID 33195)
-- Name: TaskItems PK_TaskItems; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."TaskItems"
    ADD CONSTRAINT "PK_TaskItems" PRIMARY KEY ("Id");


--
-- TOC entry 3178 (class 2606 OID 33203)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 3174 (class 2606 OID 33187)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


-- Completed on 2023-10-15 20:55:13

--
-- PostgreSQL database dump complete
--

